pod 'STHTTPRequest', '~> 1.0.0'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'NSData+MD5Digest', '~> 1.0.0'
pod 'FileMD5Hash', '~> 2.0.0'
pod 'FMDB','~>2.3'
pod 'iConsole', '~> 1.4'
pod 'SDWebImage', '~>3.6'
pod 'SWTableViewCell', '~> 0.3.7'
pod 'MJRefresh', '~> 0.0.1'
pod 'JTSImageViewController', '~> 1.4'
pod 'SVWebViewController', '~> 1.0'
pod 'EGOCache', '~> 2.1.3'
pod 'SimpleAudioPlayer'
pod 'Masonry'
pod 'SVProgressHUD'
pod 'BlocksKit'
pod 'CocoaLumberjack'
pod 'YYModel'
pod 'YYCategories'
pod 'YYCache'
pod 'YYImage'
pod 'LTNavigationBar'
pod 'AFNetworking'


#pod 'KMNavigationBarTransition'